
# Nombre de nuestro workflow
name: CI

# en que evento se va a ejecutar
on:
  # El evento sera en un push
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  

# Trabajos que queremos que haga el programa
jobs:

  build:

    # Variables de entorno
    env:
      platform: aws
      region: us-east-1
      account: 1234564789
      username: ${{secrets.USERNAME}}
      pass: ${{secrets.PASSWORD}}


    # Construira una maquina de ubuntu, la ultima version
    runs-on: ubuntu-latest

    # Pasos que hara despues de construir la maquina
    steps:
      - name: "Display message"
        run: echo "Hola mundo"
      
      - name: "Mostrando variables de entorno"
        # if: ${{env.platform == 'azure'}}
        run: |
          echo "Esto es e valor de Platform: ${{env.platform}}"
          echo "Esto es e valor de Region: ${{env.region}}"
          echo "Esto es e valor de Account: ${{env.account}}"

          echo "Este es el valor de la variable: ${{vars.PROJECT_VARS}}"
          echo "Esto es e valor de username: ${{secrets.USERNAME}}"
          echo "Esto es e valor de Password: ${{secrets.PASSWORD}}"

      - name: "Mostrando valores solo su el usuario es el correcto" 
        if: ${{env.username != '' && env.pass != ''}}
        run: |
          echo: "Si existe usuario y contraseña"

      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{toJSON(github.event)}}" # Mostrando en json
          echo "Github_ACTOR: $GITHUB_ACTOR"
          echo "Github_REPOSITORY: $GITHUB_REPOSITORY"
      