
# Nombre de nuestro workflow
name: CI

# en que evento se va a ejecutar
on:
  # El evento sera en un push
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Trabajos que queremos que haga el programa
jobs:
  
  build:
    # Construira una maquina de ubuntu, la ultima version
    runs-on: ubuntu-latest

    # Pasos que hara despues de construir la maquina
    steps:
      - name: "Display message"
        run: echo "Hola mundo"
